spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate
      database-plataform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql
      show-sql: true
